### ISSUE TITLE
Handover Units in Chapter Editor

### ISSUE THREAD

**Issue by princessblucy** [thane98/paragon#52]
[paragon.log](https://github.com/thane98/paragon/files/5099621/paragon.log)
It fails to save and the only other time I've had this issue was when trying to add a new Handover unit into a dispos, which is the same exact reason it won't save now, or at least that's all I can think of.

**Comment by thane98** [comment]
This looks like a signedness issue similar to #49 which was fixed with the latest release. Is this on [Alpha 14-3](https://github.com/thane98/paragon/releases/tag/Alpha-14-3)?

**Comment by princessblucy** [comment]
Yes it is the latest release, I've doubled checked on a new download and it still fails.
[paragon.log](https://github.com/thane98/paragon/files/5100138/paragon.log)
Here's this one's log in case it's of any use.

**Comment by thane98** [comment]
Okay. I will try to reproduce this and implement a fix.

**Comment by thane98** [comment]
This should be fixed with [64b182e](https://github.com/thane98/paragon/commit/64b182e4565d3a529bd426d5f0519471a6ff1641). It will be included in the next release, but in the meantime you can get a build with the fix [here](https://github.com/thane98/paragon/actions/runs/220800333).
